# These are supported funding model platforms
 
github: ['AIExxplorer'] # Substitua pelo seu nome de usuário do GitHub Sponsors
patreon: '' # Substitua pelo seu nome de usuário no Patreon (se aplicável)
open_collective: '' # Substitua pelo seu nome de usuário no Open Collective (se aplicável)
ko_fi: '' # Substitua pelo seu nome de usuário no Ko-fi (se aplicável)
tidelift: '' # Substitua pela URL do pacote na Tidelift (se aplicável)
community_bridge: '' # Substitua pelo nome do projeto no Community Bridge (se aplicável)
liberapay: '' # Substitua pelo seu nome de usuário no Liberapay (se aplicável)
issuehunt: '' # Substitua pelo seu nome de usuário no IssueHunt (se aplicável)
lfx_crowdfunding: '' # Substitua pelo nome do projeto no LFX Crowdfunding (se aplicável)
polar: '' # Substitua pelo seu nome de usuário no Polar (se aplicável)
buy_me_a_coffee: '' # Substitua pelo seu nome de usuário no Buy Me a Coffee (se aplicável)
thanks_dev: '' # Substitua pelo seu nome de usuário no thanks.dev (se aplicável)
custom: ['https://github.com/sponsors/AIExxplorer'] # Substitua por até 4 URLs de patrocínio personalizado
