# These are supported funding model platforms
 
github: ['AIExxplorer'] # Substitua pelo seu nome de usuário do GitHub Sponsors
custom: ['https://github.com/sponsors/AIExxplorer'] # Substitua por até 4 URLs de patrocínio personalizado
